### ISSUE TITLE
Layout bug in profile 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/together_app#54]
This bug will presumably go away when we re-do the layout to @courtbee's new designs, so i guess you can probably ignore  but fwiw:

**To reproduce**
- Boot the app in Pixel5 emulator. 
- Navigate to the profile page 

**Actual result**

I see the following in the emulator 

<img width="448" alt="image" src="https://user-images.githubusercontent.com/166867/161015449-0ee4f557-ab68-49c3-838c-62205e43430a.png">

And a warning pointing to a problem in buildUserInfoSection

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/166867/161015563-9270362b-eda5-4565-b15f-c7ccfa375024.png">

**Comment by mjxchina** [comment]
Fixed in the new profile header layout
