### ISSUE TITLE
I can't see the image after upload 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/together_app#55]
I'm guessing this is related to my brilliant idea to delete the AWS Amplify instance that said, I reset the amplify config and still getting issues. 

**Relevant context**
- I removed the dart config
` rm lib/amplifyconfiguration.dart` 
- Then re-created it with the new instance 
` amplify pull --appId d4i3jwl1gm9oi --envName dev`
- This recreated the amplifyconfiguration.dart config 

**To reproduce**
- Login as user with email address utunga@gmail.com
- Navigate to profile page in emulator
- Click to edit
- Click on image
- Choose camera.. take a photo of the fake room.. crop it 
- See a message saying 'upload success' and see this screen
<img width="361" alt="image" src="https://user-images.githubusercontent.com/166867/161016441-aa511dc1-96a7-41f5-b73f-192233085084.png">
- Hit 'save' icon

**Actual behavior**
- See a broken image or exclamation mark on the profile page
<img width="359" alt="image" src="https://user-images.githubusercontent.com/166867/161016570-4f1d9160-06b5-461b-9116-e151be11a5c1.png">
- See a different kind of seemingly broken image in the side bar thingy 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/166867/161016675-9393c123-c9ee-43a2-b9f4-33022efcd0e2.png">

**Expected behavior**
- Expect to be able to update image even if I screwed it all up in the past ?

**Comment by mjxchina** [comment]
Fixed after changing to the correct CDN domain.
